services:
  - type: web
    name: ethio-company-review
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ethio_company_review_backend.wsgi:application --worker-tmp-dir /dev/shm"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethio-company-review-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: JWT_SIGNING_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "https://yourfrontend.com,http://localhost:3000"  # Replace with your actual frontend URL
      - key: ALLOWED_HOSTS
        value: ".onrender.com,your-custom-domain.com"  # Add your Render URL (*.onrender.com)