# Generated by Django 5.1.3 on 2025-07-03 19:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='user_avatars/default.png', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
